### ISSUE TITLE
Timeout for "Waiting Authorization"

### ISSUE THREAD

**Issue by edsiper** [calyptia/core-docker-desktop-extension#62]
If the user is installing the extension just closes the authorization window without any Cancel/Accept action, the extension in "Waiting Authorization" hangs forever:

![Screen Shot 2022-10-20 at 14 54 48](https://user-images.githubusercontent.com/369718/197056241-720d6f5f-01ae-4dd3-b9c9-fc1eb756dce2.png)

Here is a quick repro:

- https://www.loom.com/share/881523bc4a5545f78fa25136bf9eb794

We need better logic to handle this kind of case, maybe a timeout before the button "Log in with browser" get's active again?

The current workaround is to go out of the extension to another menu and then back to the extension, the login option is available.

**Comment by nicolasparada** [comment]
It does have a timeout. Maybe I can put a button to open the browser again.
