### ISSUE TITLE
blockers to be published 

### ISSUE THREAD

**Issue by edsiper** [calyptia/core-docker-desktop-extension#66]
The following feedback has been received from Docker team that blocks the publish of this extension:

- [x] Remove the double quotes from the title and fix typo: “Calytia Core”
- [x] Remove the double quotes from the description: “Use Calyptia Core within Docker Desktop to manage observability.”
- [x] The detailed description is not accurate: “It will allow you to use, evaluate and test Calyptia Core without needing to deploy or use a Kubernetes cluster”. Apparently the extension requires the user to have the built-in Kubernetes cluster in Docker Desktop enabled.
- [x]  If you remove the cloud instance from the web and re-install the extension, the extension will not create a new cloud instance. It seems there are workloads of Calyptia running in K8s after the extension is removed (hardy-piledriver-a5a3_calyptia and vivo_calyptia-internal-vivo). Given the Extensions SDK doesn’t provide a hook to clean-up custom resources as part of the uninstall process, I’d advise on improving the extension to check whether Calpytia is already running on the K8s cluster.
- [x] Add a dark mode version of the extension. cc: @ariCrespo79 

Other Suggestions / Non-blocking issues:

- [x] After opening “Vivo” in the extension and sending multiple events, the “Clear” button doesn’t clear the logs.
- [ ] To use the UI component styles from the Docker extension styleguide wherever possible such the primary blue buttons etc https://www.figma.com/file/U7pLWfEf6IQKUHLhdateBI/Docker-Extensions-UI-Styleguide?node-id=1%3A28771
- [x] Change CTA from "Sure" to "Delete" as that is a more standard UX practice.

**Comment by ariCrespo79** [comment]
Dark mode version on same file, with Docker Extension Style Included:
https://www.figma.com/file/IIgNBXAJUfh4r2ZoFhgAmh/Docker-desktop-%2F-Extensions-UI-Styleguide?node-id=68%3A5423

**Comment by nicolasparada** [comment]
4) Deleting core instances from ther Core UI doesn't delete the deployment. That is not an issue that should be fixed here. I'll move that one to cloud https://github.com/calyptia/cloud/issues/650

**Comment by nicolasparada** [comment]
Just wrote the dark theme.

Still pending point 3.

> The detailed description is not accurate: “It will allow you to use, evaluate and test Calyptia Core without needing to deploy or use a Kubernetes cluster”. Apparently the extension requires the user to have the built-in Kubernetes cluster in Docker Desktop enabled.

What should I change it into?

**Comment by edsiper** [comment]
@nicolasparada you can add something like this:

```
Calyptia Core simplifies observability in your Kubernetes cluster by automating logging and optionally allows you to create custom data pipelines with support for user-defined processing rules.
```

and this one I think is still pending:

```
To use the UI component styles from the Docker extension styleguide wherever possible such the primary blue buttons etc https://www.figma.com/file/U7pLWfEf6IQKUHLhdateBI/Docker-Extensions-UI-Styleguide?node-id=1%3A28771
```

**Comment by nicolasparada** [comment]
Would be great to update the figma design then @ariCrespo79

I don't know how much should I follow the docker desktop design guideline vs calyptias'.

Docker desktop provides its own CSS on top of material design (MUI) and changes quite a bit of stuff.
